[theme]
primaryColor = "#F79A19"
backgroundColor = "#FFE52A"
secondaryBackgroundColor = "#BBCB64"
textColor = "#262730"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
showErrorDetails = false

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false